/**
 * Baked-in demo media map, keyed by lowercase exercise/move name.
 * `db`  = ExerciseDB exercise id (animated GIF via their /image endpoint, needs API key)
 * `img` = folder name in free-exercise-db (two demo frames, keyless, MIT-licensed —
 *         the app cycles the frames so these render animated, never static)
 *
 * Built offline from a full catalog crawl so the app never calls the ExerciseDB
 * *search* endpoint — only the image endpoint, and those bytes are cached locally.
 * Regenerate with scratchpad/build-gif-map.js if exercises change.
 */
export type GifMapEntry = { db?: string; img?: string };

export const GIF_MAP: Record<string, GifMapEntry> = {
  // ── chest ──
  'bench press': { db: '0025', img: 'Barbell_Bench_Press_-_Medium_Grip' },
  'incline bench press': { db: '0047', img: 'Barbell_Incline_Bench_Press_-_Medium_Grip' },
  'dumbbell bench press': { db: '0289', img: 'Dumbbell_Bench_Press' },
  'incline dumbbell press': { db: '0314', img: 'Incline_Dumbbell_Press' },
  'dumbbell floor press': { img: 'Dumbbell_Floor_Press' },
  'cable fly': { db: '0171', img: 'Flat_Bench_Cable_Flyes' },
  'push-up': { db: '0662', img: 'Pushups' },
  'incline push-up': { db: '0493', img: 'Incline_Push-Up' },
  'decline push-up': { db: '0279', img: 'Decline_Push-Up' },
  'diamond push-up': { db: '0283', img: 'Pushups' },
  'archer push-up': { db: '3294', img: 'Pushups' },
  'knee push-up': { db: '3211', img: 'Pushups' },
  'wall push-up': { img: 'Incline_Push-Up' },
  'chest dip': { db: '0251', img: 'Dips_-_Chest_Version' },
  'chair dip': { db: '0129', img: 'Bench_Dips' },
  // ── back ──
  deadlift: { db: '0032' },
  'barbell row': { db: '0027', img: 'Bent_Over_Barbell_Row' },
  'dumbbell row': { db: '0293', img: 'Bent_Over_Two-Dumbbell_Row' },
  'lat pulldown': { db: '0198', img: 'Close-Grip_Front_Lat_Pulldown' },
  'seated cable row': { db: '0861', img: 'Seated_Cable_Rows' },
  'pull-up': { db: '0652', img: 'Band_Assisted_Pull-Up' },
  'chin-up': { db: '1326', img: 'Chin-Up' },
  'assisted pull-up': { img: 'Band_Assisted_Pull-Up' },
  'assisted pull-up (band/foot)': { img: 'Band_Assisted_Pull-Up' },
  'inverted row (table/bar)': { db: '0499', img: 'Inverted_Row' },
  'face pull': { img: 'Face_Pull' },
  'back extension': { db: '0489', img: 'Hyperextensions_Back_Extensions' },
  'barbell shrug': { db: '0095', img: 'Barbell_Shrug' },
  // ── shoulders ──
  'overhead press': { db: '1456' },
  'dumbbell shoulder press': { db: '2137', img: 'Dumbbell_Shoulder_Press' },
  'lateral raise': { db: '0334', img: 'Cable_Seated_Lateral_Raise' },
  'rear delt fly': { db: '0380', img: 'Cable_Rear_Delt_Fly' },
  'pike push-up': { db: '3662', img: 'Handstand_Push-Ups' },
  'elevated pike push-up': { db: '1296', img: 'Handstand_Push-Ups' },
  'handstand push-up (wall)': { db: '0471', img: 'Handstand_Push-Ups' },
  // ── arms ──
  'barbell curl': { db: '0031', img: 'Barbell_Curl' },
  'dumbbell curl': { db: '0294', img: 'Alternate_Incline_Dumbbell_Curl' },
  'hammer curl': { db: '0313', img: 'Alternate_Hammer_Curl' },
  'cable pushdown': { db: '0201' },
  skullcrusher: { db: '0061' },
  'overhead triceps extension': { db: '0430', img: 'Cable_Rope_Overhead_Triceps_Extension' },
  'close-grip bench press': { db: '0030', img: 'Smith_Machine_Close-Grip_Bench_Press' },
  // ── legs ──
  'barbell squat': { db: '0043', img: 'Barbell_Squat' },
  'front squat': { db: '0042', img: 'Front_Squat_Clean_Grip' },
  'goblet squat': { db: '1760', img: 'Goblet_Squat' },
  'leg press': { db: '0739', img: 'Leg_Press' },
  'leg extension': { db: '0585', img: 'Leg_Extensions' },
  'leg curl': { db: '0586', img: 'Ball_Leg_Curl' },
  'romanian deadlift': { db: '0085', img: 'Romanian_Deadlift' },
  'dumbbell romanian deadlift': { db: '1459', img: 'Romanian_Deadlift' },
  'single-leg rdl': { db: '1757' },
  'bulgarian split squat': { db: '0410' },
  'walking lunge': { db: '1460', img: 'Barbell_Walking_Lunge' },
  'step-up': { db: '0114', img: 'Step-up_with_Knee_Raise' },
  'hip thrust': { db: '1409', img: 'Barbell_Hip_Thrust' },
  'glute bridge': { db: '3013', img: 'Barbell_Glute_Bridge' },
  'single-leg glute bridge': { img: 'Single_Leg_Glute_Bridge' },
  'jump squat': { db: '0514', img: 'Freehand_Jump_Squat' },
  'box squat (to chair)': { img: 'Box_Squat' },
  'standing calf raise': { db: '1490', img: 'Rocking_Standing_Calf_Raise' },
  'calf raise (bodyweight/db)': { db: '1490' },
  'seated calf raise': { db: '0594', img: 'Seated_Calf_Raise' },
  // ── core ──
  'plank (secs as reps)': { db: '2135', img: 'Plank' },
  'knee plank (secs as reps)': { img: 'Plank' },
  'hanging leg raise': { db: '0472', img: 'Hanging_Leg_Raise' },
  'hanging knee raise': { img: 'Hanging_Leg_Raise' },
  'cable crunch': { db: '0175', img: 'Cable_Crunch' },
  'bicycle crunch': { db: '0972' },
  'russian twist': { db: '0687', img: 'Russian_Twist' },
  'ab wheel rollout': { db: '0857' },
  'mountain climber': { db: '0630', img: 'Mountain_Climbers' },
  // ── full body / conditioning ──
  'kettlebell swing': { db: '0549', img: 'One-Arm_Kettlebell_Swings' },
  'farmer carry (secs as reps)': { db: '2133' },
  burpee: { db: '1160' },
  // ── cardio ──
  running: { db: '0685' },
  cycling: { db: '2138' },
  'incline walk': { db: '3666' },
  'interval sprints': { db: '0685' },
  'rowing machine': { img: 'Rowing_Stationary' },
  'stair climber': { img: 'Stairmaster' },
  'jump rope': { db: '2612' },
  'dead hang': { db: '0688' },
  'wall sit': { db: '0624' },
  'hollow hold (secs as reps)': { img: 'Flutter_Kicks' },
  // ── machines ──
  'machine chest press': { db: '0576' },
  'pec deck fly': { db: '0596' },
  'machine shoulder press': { db: '0603' },
  'machine lateral raise': { db: '0584' },
  'machine seated row': { db: '1350' },
  'machine preacher curl': { db: '0592', img: 'Machine_Preacher_Curls' },
  'machine seated dip': { db: '1451' },
  'hack squat (sled)': { db: '0743', img: 'Hack_Squat' },
  'machine seated crunch': { db: '1452' },
  // ── warmup moves ──
  'arm circles': { img: 'Arm_Circles' },
  'scapular push-up': { db: '3021' },
  'scapular pull-up': { db: '0688', img: 'Scapular_Pull-Up' },
  'cat cow': { img: 'Cat_Stretch' },
  'biceps curl': { db: '0294', img: 'Incline_Inner_Biceps_Curl' },
  squat: { db: '3533' },
  'good morning': { db: '0115', img: 'Good_Morning' },
  'hip hinge': { db: '0115' },
  'leg swing': { img: 'Standing_Hip_Circles' },
  'hip circle': { img: 'Standing_Hip_Circles' },
  'shoulder dislocate': { img: 'Shoulder_Circles' },
  'elbow circles': { img: 'Elbow_Circles' },
  'ankle circle': { db: '1368', img: 'Ankle_Circles' },
  'dead bug': { db: '0276', img: 'Dead_Bug' },
  'jumping jack': { db: '3224' },
  walk: { db: '3666' },
  // ── cooldown stretches ──
  'chest stretch': { db: '1272', img: 'Behind_Head_Chest_Stretch' },
  'shoulder stretch': { db: '1271', img: 'Shoulder_Stretch' },
  'child pose': { img: 'Childs_Pose' },
  'lat stretch': { img: 'Overhead_Lat' },
  'biceps stretch': { img: 'Standing_Biceps_Stretch' },
  'triceps stretch': { db: '0817', img: 'Triceps_Stretch' },
  'quadriceps stretch': { img: 'Quad_Stretch' },
  'hamstring stretch': { db: '1511', img: 'Hamstring_Stretch' },
  'piriformis stretch': { db: '1710' },
  'calf stretch': { db: '1377', img: 'Calf_Stretch_Elbows_Against_Wall' },
  'standing forward bend': { img: 'Standing_Toe_Touches' },
  'upward stretch': { img: 'Upward_Stretch' },
  // intentionally no demo: deep breathing (nothing to show)
};
